version: '3.7'

services:
  api:
    build: .
    container_name: api
    restart: unless-stopped
    ports:
      - "8000:8000"    
  
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    volumes:
      - './frontend:/app'
      - 'app/node_modules'
    ports:
      - "8080:8080"
    # environment:
    #   - CHOKIDAR_USEPOLLING=true

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: rest_api
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: abcd1234
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./database/CreateTable.sql:/docker-entrypoint-initdb.d/CreateTable.sql

volumes:
  db_data: